# 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
import numpy as np
arrays = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arrays)[0]
print(indices)

[0 1 4]


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [3]:
import numpy as np

my_array = np.random.rand(10, 10)

min_value = np.min(my_array)
max_value = np.max(my_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.007508949123222419
Maximum value: 0.9931099756830489


# 6. Create a random vector of size 30 and find the mean value.

In [4]:
import numpy as np
vector = np.random.rand(30)
mean_value = np.mean(vector)
print("Mean value is:", mean_value)

Mean value is: 0.45837395459869723
